#!/bin/sh
../quickemu  --help >quickemu.1-14-AllquickemuOptions-02generated.md
../quickget list_csv | awk -F"," '{print "* `" $2 "` ("$1")" }' |grep  -e buntu |sort -u  >quickemu.1-07-Ubuntus02-generated.md
../quickget list_csv | awk -F"," '{print "* `" $2 "` ("$1")" }' |grep -v -e 'Display Name' -e bsd -e windows -e  macos -e buntu -e android|sort -u >quickemu.1-08-OtherLinuxGuests02-generated.md
../quickget list_csv | awk -F"," '{print "* `" $2 "` ("$1")" }' |grep  android|sort -u  >quickemu.1-13-OtherGuests02-generated.md

echo quickemu.1-* > quickemu.lst
echo quickget.1-00-header.md quickemu.1-0[7-9]* quickemu.1-1[0-3]* quickget.1-09-footer.md > quickget.lst
# Readme header gets borked by pandoc
echo quickemu.1-0[4-6]* README-06-Install.md quickemu.1-0[7-9]* \
quickemu.1-1[0-3]* quickemu_conf.1-01-spiceheadless.md README-135-confoptions.md quickemu.1-1[4-9]* quickemu.1-2* > README.lst
#
echo quickemu_conf.1-00-hdr.md  README-135-confoptions.md quickemu_conf.1-05-footer.md > quickemu_conf.lst

pandoc -s $(cat quickemu_conf.lst)  -f markdown -t markdown -o ../quickemu_conf.1.md
pandoc -s $(cat quickemu.lst)  -f markdown -t markdown -o ../quickemu.1.md
pandoc -s $(cat quickget.lst)  -f markdown -t markdown -o ../quickget.1.md
pandoc -s $(cat README.lst)  -f markdown -t markdown -o README_main.md
## Letting the makefile build from the  markdown->markdown conversion
## gets weird.  For now build here too as these look better
## Possibly use m4 for consolidation prior to generation ???
pandoc -s $(cat quickemu.lst)  -f markdown -t man -o quickemu.1
pandoc -s $(cat quickget.lst)  -f markdown -t man -o quickget.1
pandoc -s $(cat quickemu_conf.lst)  -f markdown -t man -o quickemu_conf.1
# WARNING : these are different from those in ../ that ( cd .. && make )
# will generate
cat README-00-hdr.md README_main.md >../README.md
