#!/bin/sh
../quickemu  --help >quickemu.1-14-AllquickemuOptions-02generated.md
../quickget list_csv | awk -F"," '{print "* `" $2 "` ("$1")" }' |grep  -e buntu |sort -u  >quickemu.1-07-Ubuntus02-generated.md
../quickget list_csv | awk -F"," '{print "* `" $2 "` ("$1")" }' |grep -v -e 'Display Name' -e bsd -e windows -e  macos -e buntu -e android|sort -u >quickemu.1-08-OtherLinuxGuests02-generated.md
../quickget list_csv | awk -F"," '{print "* `" $2 "` ("$1")" }' |grep -e bsd |sort -u >quickemu.1-08bsd-BSDGuests-generated.md
../quickget list_csv | awk -F"," '{print "* `" $2 "` ("$1")" }' |grep  android|sort -u  >quickemu.1-13-OtherGuests02-generated.md

echo quickemu.1-* > quickemu.lst
echo quickget.1-00-header.md quickemu.1-0[7-9]* quickemu.1-1[0-3]* quickget.1-09-footer.md > quickget.lst
# Readme header gets borked by pandoc
echo quickemu.1-0[4-6]* README-06-Install.md quickemu.1-0[7-9]* \
quickemu.1-1[0-3]* quickemu_conf.1-01-spiceheadless.md README-135-confoptions.md quickemu.1-1[4-9]* quickemu.1-2* > README.lst
#
echo quickemu_conf.1-00-hdr.md  README-135-confoptions.md quickemu_conf.1-05-footer.md > quickemu_conf.lst

pandoc -s $(cat quickemu_conf.lst)  -f markdown -t markdown -o ../docs/quickemu_conf.1.md
pandoc -s $(cat quickemu.lst)  -f markdown -t markdown -o ../docs/quickemu.1.md
pandoc -s $(cat quickget.lst)  -f markdown -t markdown -o ../docs/quickget.1.md
#
pandoc -s $(cat quickemu.lst)  -f markdown -t man -o ../docs/quickemu.1
pandoc -s $(cat quickget.lst)  -f markdown -t man -o ../docs/quickget.1
pandoc -s $(cat quickemu_conf.lst)  -f markdown -t man -o ../docs/quickemu_conf.1

pandoc -s $(cat README.lst)  -f markdown -t markdown -o README_main.md
#
cat README-00-hdr.md README_main.md >../README.md
