name: NodeJS with Webpack

on:
    push:
        tags:
            - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    # Ne s'exécute que lorsqu'un tag est poussé
    if: startsWith(github.ref, 'refs/tags/')

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx less src/css/ékrityr-snow.less src/css/ékrityr-snow.css
        npx webpack

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Prepare release directory
      run: |
        mkdir -p _release
        mkdir -p _release_tmp/dist 
        # Copier uniquement les fichiers nécessaires
        cp -r dist/* _release_tmp/dist/
        cp *.html _release_tmp/
        cp README.md _release_tmp/

    - name: Create archives
      run: |
        cd _release_tmp
        zip -r "../_release/ékrityr-${{ env.VERSION }}.zip" .
        tar -czf "../_release/ékrityr-${{ env.VERSION }}.tar.gz" .
        cd ..

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.VERSION }}
        files: |
          _release/ékrityr-${{ env.VERSION }}.zip
          _release/ékrityr-${{ env.VERSION }}.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}